### PR TITLE
Change bech32 address prefixes

### PR DESCRIPTION
**Pull request by oxarbitrage**
As  we discussed in discord there are some errors with the key manager:

```
2020-06-03T16:27:20Z [default wallet] External scriptPubKey Manager for output type 0 does not exist
2020-06-03T16:27:20Z [default wallet] External scriptPubKey Manager for output type 1 does not exist
2020-06-03T16:27:20Z [default wallet] External scriptPubKey Manager for output type 2 does not exist
```
However this errors are there without this changes too, i am not 100% sure but it seems the address prefix changes is not affecting overall functionality, at least i can see keys generated fine with:

```
$ ./src/ghost-cli -testnet getnewaddress "" true
tgsth1g5rn9eetjze8sqr7ssv7808q0y6xamn622tc2u
$
```

I also made the changes in the python as i found the `tgw` prefix there however i am not sure if some of the other parameters in the templates should be modified too.

### CODE REVIEW

**Comment by TheQuantumPhysicist** [comment]
Did you run the full set of unit tests and system tests?

**Comment by oxarbitrage** [comment]
Thank you for that. 

I tried the unit tests and there are problems with the key_io tests:

```
$ ./src/test/test_ghost 
Running 460 test cases...
test/key_io_tests.cpp(58): error: in "key_io_tests/key_io_valid_parse": !IsValid:["tgstw1qqwl46dyeg65rnu6x6h4dxlpskda7gvvt3z0dwt","001403bf5d349946a839f346d5ead37c30b37be4318b",{"chain":"test","isPrivkey":false,"tryCaseFlip":true}]
test/key_io_tests.cpp(59): error: in "key_io_tests/key_io_valid_parse": check HexStr(script) == HexStr(exp_payload) has failed [ != 001403bf5d349946a839f346d5ead37c30b37be4318b]
test/key_io_tests.cpp(70): error: in "key_io_tests/key_io_valid_parse": !IsValid case flipped:["tgstw1qqwl46dyeg65rnu6x6h4dxlpskda7gvvt3z0dwt","001403bf5d349946a839f346d5ead37c30b37be4318b",{"chain":"test","isPrivkey":false,"tryCaseFlip":true}]
test/key_io_tests.cpp(58): error: in "key_io_tests/key_io_valid_parse": !IsValid:["tgstw1q50sqppj9fgdppskywmvdg5avu4ph5jdk3z27lpnws9jjxp5wurtqptpf8f","0020a3e00086454a1a10c2c476d8d453ace5437a49b68895ef866e816523068ee0d6",{"chain":"test","isPrivkey":false,"tryCaseFlip":true}]
...
```

We need to change the valid and invalid jsons. The invalid is trivial, we can just change the prefixes from `tgw` to `tgstw`: https://github.com/ghost-coin/ghost-private/blob/master/src/test/data/key_io_invalid.json

The valid ones are harder as we need to change the hash of the address https://github.com/ghost-coin/ghost-private/blob/master/src/test/data/key_io_valid.json

Any help on how to generate those is welcome.

**Comment by akshaynexus** [comment]
https://github.com/ghost-coin/ghost-private/blob/master/contrib/testgen/README.md

see that on how to generate the proper key_io json files.

**Comment by TheQuantumPhysicist** [comment]
We cannot do any merge without having all tests work (except for those who didn't work before your PR).

**Comment by oxarbitrage** [comment]
> We cannot do any merge without having all tests work (except for those who didn't work before your PR).

Yea, that's clear, my mistake.

I was able to generate key_io json files with the link provided, now the `key_io_tests` are passing.

All the HD tests are failing so i had to disable them, failures also occur in `stake_test`. All this happening without the changes in this PR(current master).

With that said, the unit tests should be now covered. 
Please dont merge yet, need to check the functional tests.

**Comment by oxarbitrage** [comment]
I can confirm the functional tests are all passing except for `feature_dbcrash.py` which is well known issue.

**Comment by TheQuantumPhysicist** [comment]
Akshay, doesn't this break our current testnet? So we have to launch it again? Are we OK with that?

**Comment by akshaynexus** [comment]
i dont think this breaks the current testnet,since we havent used any bech32 addresses in txes afaik

**Review by TheQuantumPhysicist — APPROVED** [review]

**Comment by gmkaddar** [comment]
This shouldn't have been merged, wrong prefix.

**Pull request merged**
