### PR TITLE
Change origin of hidapi package in depends

### PR DESCRIPTION
**Pull request by Chesbob**
The libusb team has taken over maintenance of the hidapi repository some time ago, we should be using their repository as a source.

### CODE REVIEW

**Comment by akshaynexus** [comment]
Have you tried compiling after this change was done?

**Comment by Chesbob** [comment]
I compiled it with depends, and configured with `--enable-usbdevice` and the compilation ran fine. I'm not familiar with the usbdevice functionality, so I'd appreciate if you could give it a test as well.

**Review by gmkaddar — APPROVED** [review]
The libusb hidapi library works for me on windows running node + ledger which is the point of this thing. 
Good work!

**Review by akshaynexus — APPROVED** [review]
LGTM

**Pull request merged**
